### ISSUE TITLE
organize ansible host/groups and ssh vars

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#426]
we have playbooks like update_asterisk_playbook.yml

```
---
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: update_asterisk.yml
    - include: update_asterisk_sounds.yml    
- hosts: virtualbox
  become: true
  tasks:
    - include: update_asterisk.yml
    - include: update_asterisk_sounds.yml    
```

and baseinstall_playbook.yml

```
---
- hosts: baseinstall:virtualbox
  become: true
  vars:
    src: "../src"
  tasks:
    - include: packages.yml
    - include: users.yml
    - include: config.yml
    - include: install_misc.yml
    - include: install_asterisk.yml
```

this is basically because we only want ssh vars on DO boxes, not virtualbox boxes, and also it takes an ansible play to make the SSH attrs, so there is a moment when DO boxes don't use the SSH attrs. And because of an ansible bug/detail we can't assign the same host to 2 groups without sharing vars.

Take ssh vars out of playbooks, use var files or some other form of ansible organziation
We should probably upgrade to roles to organize these, this might help with the host var issue too
